import { useEffect, useState } from "react";
import { CalendarDays, CheckCircle, Clock, Save } from "lucide-react";
import { Card, CardHeader, CardTitle, CardDescription, CardContent } from "../components/ui/Card";
import { Input, Label } from "../components/ui/Input";
import { Select } from "../components/ui/Select";
import { Button } from "../components/ui/Button";

type Settings = {
  shift: { enabled: boolean; startTime: string; maxHours: number; breakMinutes: number; workDays: number };
  lateness: { enabled: boolean; graceMinutes: number; lateThresholdMinutes: number; penaltyRate: number };
  leave: { enabled: boolean; casualDays: number; sickDays: number; frequency: string; carryOverDays: number };
};

const defaults: Settings = {
  shift: { enabled: false, startTime: "09:00", maxHours: 8, breakMinutes: 60, workDays: 5 },
  lateness: { enabled: false, graceMinutes: 15, lateThresholdMinutes: 30, penaltyRate: 1 },
  leave: { enabled: false, casualDays: 10, sickDays: 10, frequency: "monthly", carryOverDays: 5 },
};

function Toggle({ enabled, onChange }: { enabled: boolean; onChange: (enabled: boolean) => void }) {
  return <button type="button" role="switch" aria-checked={enabled} onClick={() => onChange(!enabled)} className={`relative h-6 w-11 rounded-full transition ${enabled ? "bg-[#8642ED]" : "bg-slate-300"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white shadow transition-all ${enabled ? "left-6" : "left-1"}`} /></button>;
}

export function SettingsView() {
  const [settings, setSettings] = useState<Settings>(defaults);
  const [saved, setSaved] = useState(false);
  const [saving, setSaving] = useState(false);

  useEffect(() => { fetch("http://localhost:5000/api/settings").then((response) => response.ok ? response.json() : Promise.reject()).then((data) => setSettings({ ...defaults, ...data })).catch(() => {}); }, []);
  const setSection = <K extends keyof Settings>(section: K, value: Partial<Settings[K]>) => setSettings((current) => ({ ...current, [section]: { ...current[section], ...value } }));
  const save = async () => { setSaving(true); try { const response = await fetch("http://localhost:5000/api/settings", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); if (!response.ok) throw new Error(); setSettings(await response.json()); setSaved(true); setTimeout(() => setSaved(false), 2500); } finally { setSaving(false); } };

  return <div className="space-y-6">
    <div><h2 className="text-2xl font-bold text-slate-900">Company Settings</h2><p className="text-sm text-slate-500">Disabled cards have no effect. Payroll is always calculated in fixed 15-day periods.</p></div>
    <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
      <Card className={!settings.shift.enabled ? "opacity-75" : ""}><CardHeader><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-100"><Clock className="h-5 w-5 text-[#8642ED]" /></div><div><CardTitle>Work Hour Control</CardTitle><CardDescription>Automatically clock out employees at the allowed limit</CardDescription></div></div><Toggle enabled={settings.shift.enabled} onChange={(enabled) => setSection("shift", { enabled })} /></div></CardHeader><CardContent className="space-y-4" aria-disabled={!settings.shift.enabled}><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Shift Start</Label><Input disabled={!settings.shift.enabled} type="time" value={settings.shift.startTime} onChange={(e) => setSection("shift", { startTime: e.target.value })} /></div><div className="space-y-2"><Label>Maximum Paid Hours</Label><Input disabled={!settings.shift.enabled} className="no-number-arrows" type="number" min="1" max="24" step="0.5" value={settings.shift.maxHours || ""} onChange={(e) => setSection("shift", { maxHours: Number(e.target.value) })} /></div></div><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Unpaid Break (minutes)</Label><Input disabled={!settings.shift.enabled} className="no-number-arrows" type="number" min="0" value={settings.shift.breakMinutes || ""} onChange={(e) => setSection("shift", { breakMinutes: Number(e.target.value) })} /></div><div className="space-y-2"><Label>Work Days Per Week</Label><Select disabled={!settings.shift.enabled} value={settings.shift.workDays} onChange={(e) => setSection("shift", { workDays: Number(e.target.value) })}><option value="5">5 days (Mon–Fri)</option><option value="6">6 days (Mon–Sat)</option><option value="7">7 days</option></Select></div></div><p className="rounded-lg bg-violet-50 p-3 text-xs text-violet-700">When enabled, employees still clocked in are automatically clocked out once they reach this limit. Overtime cannot accumulate beyond it.</p></CardContent></Card>
      <Card className={!settings.lateness.enabled ? "opacity-75" : ""}><CardHeader><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50"><Clock className="h-5 w-5 text-amber-600" /></div><div><CardTitle>Grace Period & Lateness</CardTitle><CardDescription>Late clock-in rules</CardDescription></div></div><Toggle enabled={settings.lateness.enabled} onChange={(enabled) => setSection("lateness", { enabled })} /></div></CardHeader><CardContent className="space-y-4"><div className="space-y-2"><Label>Grace Period (minutes)</Label><Input disabled={!settings.lateness.enabled} className="no-number-arrows" type="number" value={settings.lateness.graceMinutes || ""} onChange={(e) => setSection("lateness", { graceMinutes: Number(e.target.value) })} /></div><div className="space-y-2"><Label>Late Threshold (minutes)</Label><Input disabled={!settings.lateness.enabled} className="no-number-arrows" type="number" value={settings.lateness.lateThresholdMinutes || ""} onChange={(e) => setSection("lateness", { lateThresholdMinutes: Number(e.target.value) })} /></div><div className="space-y-2"><Label>Penalty Rate (%)</Label><Input disabled={!settings.lateness.enabled} className="no-number-arrows" type="number" step="0.5" value={settings.lateness.penaltyRate || ""} onChange={(e) => setSection("lateness", { penaltyRate: Number(e.target.value) })} /></div></CardContent></Card>
      <Card className={!settings.leave.enabled ? "opacity-75" : ""}><CardHeader><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50"><CalendarDays className="h-5 w-5 text-emerald-600" /></div><div><CardTitle>Leave Accrual Rules</CardTitle><CardDescription>Annual leave credit allocation</CardDescription></div></div><Toggle enabled={settings.leave.enabled} onChange={(enabled) => setSection("leave", { enabled })} /></div></CardHeader><CardContent className="space-y-4"><div className="grid grid-cols-2 gap-4"><div className="space-y-2"><Label>Casual Leave</Label><Input disabled={!settings.leave.enabled} className="no-number-arrows" type="number" value={settings.leave.casualDays || ""} onChange={(e) => setSection("leave", { casualDays: Number(e.target.value) })} /></div><div className="space-y-2"><Label>Sick Leave</Label><Input disabled={!settings.leave.enabled} className="no-number-arrows" type="number" value={settings.leave.sickDays || ""} onChange={(e) => setSection("leave", { sickDays: Number(e.target.value) })} /></div></div><div className="space-y-2"><Label>Accrual Frequency</Label><Select disabled={!settings.leave.enabled} value={settings.leave.frequency} onChange={(e) => setSection("leave", { frequency: e.target.value })}><option value="monthly">Monthly</option><option value="quarterly">Quarterly</option><option value="annual">Annual</option></Select></div><div className="space-y-2"><Label>Carry-over Limit</Label><Input disabled={!settings.leave.enabled} className="no-number-arrows" type="number" value={settings.leave.carryOverDays || ""} onChange={(e) => setSection("leave", { carryOverDays: Number(e.target.value) })} /></div></CardContent></Card>
    </div>
    <div className="flex items-center justify-end gap-3">{saved && <span className="flex items-center gap-1.5 text-sm font-medium text-emerald-600"><CheckCircle className="h-4 w-4" />Settings saved</span>}<Button variant="outline" onClick={() => setSettings(defaults)}>Reset to Defaults</Button><Button onClick={save} disabled={saving}><Save className="h-4 w-4" />{saving ? "Saving..." : "Save Changes"}</Button></div>
  </div>;
}
