export function additionFrequency(item: { frequency?: string }): 'quarterly' | 'per-payroll';
export function quarterForDate(date: string): string;
export function validQuarter(quarter: unknown): boolean;
export function quarterLabel(quarter: string): string;
export function nextQuarter(quarter: string): string;
export function allowanceKey(item: { sourceKey?: string; type?: string; label?: string }): string;
export const COMBINED_ADDITION_KEY: string;
export function combinedSalaryAddition(employee: { salaryAddition?: { amount: number; frequency: 'quarterly' | 'per-payroll' }; identifiers?: { amount: number; frequency?: string; eligibleFromQuarter?: string }[] }): { amount: number; frequency: 'quarterly' | 'per-payroll'; eligibleFromQuarter?: string };
export function scheduleSalaryAddition(existing: unknown, incoming: { amount: number; frequency: 'quarterly' | 'per-payroll' }, today?: string, newAllowanceQuarter?: string): { amount: number; frequency: 'quarterly' | 'per-payroll'; eligibleFromQuarter: string; frequencyHistory: { fromQuarter: string; frequency: 'quarterly' | 'per-payroll' }[] };
export function manilaDate(date?: Date): string;
export function frequencyForQuarter(item: { frequency?: string; frequencyHistory?: { fromQuarter: string; frequency: string }[] }, quarter: string): string | null;
export function configuredAdditions(employee: { salaryAddition?: { amount: number; frequency: string; eligibleFromQuarter?: string; frequencyHistory?: { fromQuarter: string; frequency: string }[] }; identifiers?: { type: string; value: string; amount: number; frequency?: string }[] }, frequency: 'quarterly' | 'per-payroll', quarter?: string): { label: string; value: number; quarter?: string }[];
